version: "3"
services:
  node:
    image: "node"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.2"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - redis-net
    command: "npm start"
    environment:
      - NODE_ENV=production
      - ServiceUsername
      - ServicePassword
      - StravaClientId
      - StravaClientSecret
      - ZwiftRateLimit=25
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis
    networks:
      - redis-net
    hostname: redis
    volumes:
      - ../data/redis:/data
    restart: always

networks:
  redis-net:
  